# Site settings
title: Arroios
description: Lorem ipsum dolor est

author: João Arroios
email: joaoarroios@gmail.com
twitter_username: #
github_username: #

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arroios.com.br" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

